#98: Allow PR deployments into dev environment via comments

diff --git a/.github/workflows/build-and-push-docker-image.yml b/.github/workflows/build-and-push-docker-image.yml
--- a/.github/workflows/build-and-push-docker-image.yml
+++ b/.github/workflows/build-and-push-docker-image.yml
@@ -1,6 +1,6 @@
 # This Github workflow only builds a Docker image, it will not publish it to the AWS ECR private registry.
 name: build-and-push-docker-image
-run-name: Build and push docker image for ${{ inputs.BRANCH != '' && inputs.BRANCH || format('PR-{0}-{1}', github.event.client_payload.github.payload.issue.number, github.event.client_payload.pull_request.head.sha) }}
+run-name: Build and push docker image for ${{ inputs.BRANCH != '' && inputs.BRANCH || format('PR-{0}', github.event.client_payload.github.payload.issue.number) }}
 
 on:
   workflow_dispatch:
@@ -15,7 +15,7 @@ on:
         required: true
 
   repository_dispatch:
-    types: [ "docker:push-command" ]
+    types: [ "docker:push-command", "ec2:deploy-command" ]
 
 env:
   PROD_AWS_ACCOUNT_ID: 780602547172
@@ -23,7 +23,7 @@ env:
   AWS_REGION: us-east-1
   ECR_REPOSITORY: kinsend-sqs-consumer
   GIT_REF: ${{ inputs.BRANCH != '' && inputs.BRANCH || github.event.client_payload.pull_request.head.sha }}
-  IMAGE_REF: ${{ inputs.BRANCH != '' && inputs.BRANCH || format('PR-{0}-{1}', github.event.client_payload.github.payload.issue.number, github.event.client_payload.pull_request.head.sha) }}
+  IMAGE_REF: ${{ inputs.BRANCH != '' && inputs.BRANCH || format('PR-{0}', github.event.client_payload.github.payload.issue.number) }}
 
 # These permissions are required to allow writing comments and reporting check status.
 permissions:
@@ -46,8 +46,11 @@ jobs:
           ref: ${{ env.GIT_REF }}
 
       - name: Get git commit hash
-        uses: pr-mpt/actions-commit-hash@v2
         id: commit
+        run: |
+          short_sha=$(git rev-parse --short HEAD)
+          echo "Short sha is: ${short_sha}"
+          echo "short=$short_sha" >> $GITHUB_OUTPUT
 
       - name: Configure dynamic variables
         id: vars
@@ -60,16 +63,18 @@ jobs:
           accountId=${{ env.DEV_AWS_ACCOUNT_ID }}
           roleId="dev"
           version=1.0.0-${{ env.IMAGE_REF }}
+          manifestVersion=$version-${{ steps.commit.outputs.short }}
 
           if [[ "$ref" == "master" || "$ref" == "main" ]]; then
             accountId=${{ env.PROD_AWS_ACCOUNT_ID }};
             roleId="prod"
             version=1.0.0-master-${{ steps.commit.outputs.short }}
-          fi
-          if [[ "$ref" == "develop" ]]; then
+            manifestVersion=$version
+          elif [[ "$ref" == "develop" ]]; then
             # We are not using "version", because for the `develop` branch the version is fixed to just `1.0.0-develop`
             # without a hash to reduce the need for cleaning up old or one-time versions from ECR.
             version=1.0.0-develop-${{ steps.commit.outputs.short }}
+            manifestVersion=$version
           fi
 
           registry="${accountId}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com"
@@ -80,11 +85,14 @@ jobs:
           echo "Role: ${roleId}"
           echo "Repository: ${repository}"
           echo "Version: ${version}"
+          echo "Manifest version: ${manifestVersion}"
           echo "Image: ${image}"
           
           echo "accountId=$accountId" >> $GITHUB_OUTPUT 
           echo "roleId=$roleId" >> $GITHUB_OUTPUT 
           echo "registry=$registry" >> $GITHUB_OUTPUT
+          echo "version=$version" >> $GITHUB_OUTPUT
+          echo "manifestVersion=$manifestVersion" >> $GITHUB_OUTPUT
           echo "image=$image" >> $GITHUB_OUTPUT
 
       - name: Configure AWS credentials
@@ -101,11 +109,66 @@ jobs:
 
       - name: Build ${{ steps.vars.outputs.image }}
         run: |
-          docker build --no-cache -t ${{ steps.vars.outputs.image }} .
+          docker build --no-cache --build-arg "MANIFEST_VERSION=${{ steps.vars.outputs.manifestVersion }}" -t ${{ steps.vars.outputs.image }} .
 
       - name: Push ${{ steps.vars.outputs.image }}
         run: |
           docker push ${{ steps.vars.outputs.image }}
+
+      - name: Deploy SQS consumer to EC2 developer cluster (on demand)
+        if: ${{ env.GIT_REF == 'develop' || github.event.client_payload.slash_command.command == 'ec2:deploy' }}
+        id: deployment
+        run: |
+          # For easier development
+          if [[ -z $GITHUB_OUTPUT ]]; then
+            GITHUB_OUTPUT=/dev/stdout
+          fi
+
+          GH_VER='${{ steps.vars.outputs.version }}'
+          VERSION=${1:-$GH_VER} # for local dev - the first argument to the script will become the version.
+
+          set -exuo pipefail;
+
+          echo "Preparing to deploy new version: $VERSION" > /dev/null
+
+          echo "Print currently deployed sqs image version" > /dev/null
+          aws ssm get-parameter --name kinsend.sqs.dev.image_version
+
+          echo "Update sqs version parameter to $VERSION" > /dev/null
+          aws ssm put-parameter --overwrite --type String --name kinsend.sqs.dev.image_version --value $VERSION
+
+          echo "Scale EC2 instance down" > /dev/null
+          scalingGroup=$(aws autoscaling describe-auto-scaling-groups | jq -er '.AutoScalingGroups | .[] | select(.AutoScalingGroupName | startswith("kinsend-sqs-agent-")) | .AutoScalingGroupName')
+          aws autoscaling update-auto-scaling-group --auto-scaling-group-name $scalingGroup --min-size 0 --desired-capacity 0
+
+          echo "Waiting..." > /dev/null
+          sleep 15
+
+          echo "Scaling EC2 instance up" > /dev/null
+          aws autoscaling update-auto-scaling-group --auto-scaling-group-name $scalingGroup --min-size 1 --desired-capacity 1
+
+          echo "Waiting for EC2 instance to boot." > /dev/null
+          i="0"
+          while true; do
+
+            if [[ $i -gt 15 ]]; then
+              echo "Error -- EC2 instance did not boot! Manual intervention is required."
+              exit 1
+            fi
+
+            rawState=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].[InstanceId,IamInstanceProfile,State]' --filters Name=instance-state-name,Values=running Name=tag:aws:autoscaling:groupName,Values=$scalingGroup | jq -r '.[] | .[]')
+            state=$(echo "$rawState" | jq -r '.[2].Name')
+            instanceId=$(echo "$rawState" | jq -r '.[0]')
+
+            if [[ "$state" == "running" ]]; then
+              echo "instanceId=$instanceId" >> $GITHUB_OUTPUT
+              break;
+            fi
+
+            echo "No running EC2 instance found. Waiting 30 seconds." > /dev/null
+            sleep 30
+            i=$((i + 1))
+          done
 
       - name: Post Docker clean-up
         if: ${{ always() }}
@@ -144,15 +207,20 @@ jobs:
             #### Status
             
             🟢 Docker image `${{ steps.vars.outputs.image }}` was successfully pushed.
-            
+            ${{ github.event.client_payload.slash_command.command == 'ec2:deploy' && format('🟢 Image `{0}` was deployed to a new EC2  instance', steps.vars.outputs.image) || '🔵 Image deployment was skipped.' }}  
+
             #### Build log
             
             For more details check the [build log](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).            
 
-            #### Test
+            #### Test 
             
             1. Authenticate via `docker login ${{ steps.vars.outputs.registry }}`
-            2. Execute the following to test the image:
+
+            2. Execute the following to test the image locally:
                ```
                docker run -it --rm ${{ steps.vars.outputs.image }}
                ```
+
+            3. [Check instance via the management console](https://${{ env.AWS_REGION }}.aws.amazon.com/ec2/home?region=us-east-1#InstanceDetails:instanceId=${{ steps.deployment.outputs.instanceId }}) (if image was deployed)  
+               Note: It takes between 2 to 5 minutes for the new EC2 instance to boot the new docker container. Be patient.
